### PR TITLE
Importance of avoiding duplication

### PR DESCRIPTION
**Pull request by nteich01**

### CODE REVIEW

**Comment by nteich01** [comment]
@michaelrson @fabbroad @rionike @angelama2126  Can you take a look and suggest edits?

Thanks!

**Comment by rionike** [comment]
I liked your summary of your takeaways - maybe you would want to consider adding a short description of what the video is about.

**Comment by nteich01** [comment]
@rionike Thanks, added description of video

**Comment by michaelrson** [comment]
Perhaps you can include the common types of duplication such as imposed, inadvertent, impatient, and interdeveloper just to highlight places where you can watch out for this.  Otherwise, agree with everything you wrote.

**Comment by nteich01** [comment]
@michaelrson Thanks, added

**Pull request merged**
